/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Zbook G3
 */
public class FrmAddExamination extends javax.swing.JDialog {

    /**
     * Creates new form FrmAddExamination
     */
    public FrmAddExamination(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAddExamination = new javax.swing.JPanel();
        pnTermin = new javax.swing.JPanel();
        lblTermin = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblTheEnd = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnScheduledTermins = new javax.swing.JButton();
        txtStartHours = new javax.swing.JTextField();
        txtStartMinutes = new javax.swing.JTextField();
        txtTheEndMinutes = new javax.swing.JTextField();
        txtTheEndHours = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblTotalDuration = new javax.swing.JLabel();
        lblCurrentDuration = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        cbPatient = new javax.swing.JComboBox<>();
        txtCurrentDoctor = new javax.swing.JTextField();
        txtTotalDuration = new javax.swing.JTextField();
        txtTotalPrice = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPatient = new javax.swing.JTextField();
        btnChoosePatient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        btnDeleteItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        cbService = new javax.swing.JComboBox<>();
        btnAddItem = new javax.swing.JButton();
        btnEnableChanges = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSaveAll = new javax.swing.JButton();
        btnCancelAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnTermin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTermin.setToolTipText("");
        pnTermin.setName(""); // NOI18N

        lblTermin.setText("Termin:");

        lblStart.setText("Start:");

        lblTheEnd.setText("The end:");

        lblDate.setText("Date:");

        btnScheduledTermins.setText("Scheduled termin");
        btnScheduledTermins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduledTerminsActionPerformed(evt);
            }
        });

        jLabel1.setText(":");

        jLabel2.setText(":");

        javax.swing.GroupLayout pnTerminLayout = new javax.swing.GroupLayout(pnTermin);
        pnTermin.setLayout(pnTerminLayout);
        pnTerminLayout.setHorizontalGroup(
            pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTerminLayout.createSequentialGroup()
                .addComponent(lblTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnTerminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTheEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScheduledTermins, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnTerminLayout.createSequentialGroup()
                        .addComponent(txtTheEndHours, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTheEndMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTerminLayout.createSequentialGroup()
                        .addComponent(txtStartHours, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(txtStartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnTerminLayout.setVerticalGroup(
            pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTerminLayout.createSequentialGroup()
                .addComponent(lblTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartHours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheEndMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheEndHours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnScheduledTermins, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblID.setText("ID:");

        lblTotalPrice.setText("Total price:");

        lblTotalDuration.setText("Total duration:");

        lblCurrentDuration.setText("Current doctor:");

        lblPatient.setText("Patient:");

        cbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChoosePatient.setText("Choose patient");

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(cbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn1Layout.createSequentialGroup()
                        .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn1Layout.createSequentialGroup()
                                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn1Layout.createSequentialGroup()
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn1Layout.createSequentialGroup()
                                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn1Layout.createSequentialGroup()
                                        .addComponent(lblTotalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn1Layout.createSequentialGroup()
                                        .addComponent(lblCurrentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCurrentDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnChoosePatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pn1Layout.createSequentialGroup()
                                .addComponent(lblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoosePatient))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItems);

        btnDeleteItem.setText("Delete item");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblItem.setText("Item");

        lblPrice.setText("Price:");

        lblDuration.setText("Duration:");

        lblNote.setText("Note:");

        lblService.setText("Service:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        cbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddItem.setText("Add item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblService, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbService, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbService, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblService, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnEnableChanges.setText("Enable changes");

        btnEdit.setText("Edit");

        btnDelete.setText("Delete");

        btnSaveAll.setText("Save");

        btnCancelAll.setText("Cancel");

        javax.swing.GroupLayout pnAddExaminationLayout = new javax.swing.GroupLayout(pnAddExamination);
        pnAddExamination.setLayout(pnAddExaminationLayout);
        pnAddExaminationLayout.setHorizontalGroup(
            pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddExaminationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnAddExaminationLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAddExaminationLayout.createSequentialGroup()
                        .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(pnTermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAddExaminationLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258)
                        .addComponent(btnEnableChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnAddExaminationLayout.createSequentialGroup()
                        .addGap(677, 677, 677)
                        .addGroup(pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnAddExaminationLayout.setVerticalGroup(
            pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddExaminationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTermin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnAddExaminationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddExaminationLayout.createSequentialGroup()
                        .addComponent(btnEnableChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSaveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTermin.getAccessibleContext().setAccessibleName("AAJDEE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAddExamination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAddExamination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScheduledTerminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduledTerminsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScheduledTerminsActionPerformed

    /**
     * @param args the command line arguments
     */
   
    /**
     * @return the btnAddItem
     */
    public javax.swing.JButton getBtnAddItem() {
        return btnAddItem;
    }

    /**
     * @param btnAddItem the btnAddItem to set
     */
    public void setBtnAddItem(javax.swing.JButton btnAddItem) {
        this.btnAddItem = btnAddItem;
    }

    /**
     * @return the btnCancelAll
     */
    public javax.swing.JButton getBtnCancelAll() {
        return btnCancelAll;
    }

    /**
     * @param btnCancelAll the btnCancelAll to set
     */
    public void setBtnCancelAll(javax.swing.JButton btnCancelAll) {
        this.btnCancelAll = btnCancelAll;
    }

    /**
     * @return the btnDelete
     */
    public javax.swing.JButton getBtnDelete() {
        return btnDelete;
    }

    /**
     * @param btnDelete the btnDelete to set
     */
    public void setBtnDelete(javax.swing.JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    /**
     * @return the btnEdit
     */
    public javax.swing.JButton getBtnEdit() {
        return btnEdit;
    }

    /**
     * @param btnEdit the btnEdit to set
     */
    public void setBtnEdit(javax.swing.JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    /**
     * @return the btnEnableChanges
     */
    public javax.swing.JButton getBtnEnableChanges() {
        return btnEnableChanges;
    }

    /**
     * @param btnEnableChanges the btnEnableChanges to set
     */
    public void setBtnEnableChanges(javax.swing.JButton btnEnableChanges) {
        this.btnEnableChanges = btnEnableChanges;
    }

    /**
     * @return the btnMakeTermin
     */
    public javax.swing.JButton getBtnScheduledTermins() {
        return btnScheduledTermins;
    }

    /**
     * @param btnMakeTermin the btnMakeTermin to set
     */
    public void setBtnScheduledTermins(javax.swing.JButton btnMakeTermin) {
        this.btnScheduledTermins = btnMakeTermin;
    }

    

    /**
     * @return the btnSave1
     */
    public javax.swing.JButton getBtnDeleteItem() {
        return btnDeleteItem;
    }

    /**
     * @param btnSave1 the btnSave1 to set
     */
    public void setBtnDeleteItem(javax.swing.JButton btnSave1) {
        this.btnDeleteItem = btnSave1;
    }

    /**
     * @return the btnSaveAll
     */
    public javax.swing.JButton getBtnSaveAll() {
        return btnSaveAll;
    }

    /**
     * @param btnSaveAll the btnSaveAll to set
     */
    public void setBtnSaveAll(javax.swing.JButton btnSaveAll) {
        this.btnSaveAll = btnSaveAll;
    }

    /**
     * @return the cbPatient
     */
    public javax.swing.JComboBox<Object> getCbPatient() {
        return cbPatient;
    }

    /**
     * @param cbPatient the cbPatient to set
     */
    public void setCbPatient(javax.swing.JComboBox<Object> cbPatient) {
        this.cbPatient = cbPatient;
    }

    /**
     * @return the cbService
     */
    public javax.swing.JComboBox<Object> getCbService() {
        return cbService;
    }

    /**
     * @param cbService the cbService to set
     */
    public void setCbService(javax.swing.JComboBox<Object> cbService) {
        this.cbService = cbService;
    }

    /**
     * @return the dateTermin
     */
    public de.wannawork.jcalendar.JCalendarComboBox getDateTermin() {
        return dateTermin;
    }

    /**
     * @param dateTermin the dateTermin to set
     */
    public void setDateTermin(de.wannawork.jcalendar.JCalendarComboBox dateTermin) {
        this.dateTermin = dateTermin;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getLblItem() {
        return lblItem;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setLblItem(javax.swing.JLabel lblItem) {
        this.lblItem = lblItem;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the lblCurrentDuration
     */
    public javax.swing.JLabel getLblCurrentDuration() {
        return lblCurrentDuration;
    }

    /**
     * @param lblCurrentDuration the lblCurrentDuration to set
     */
    public void setLblCurrentDuration(javax.swing.JLabel lblCurrentDuration) {
        this.lblCurrentDuration = lblCurrentDuration;
    }

    /**
     * @return the lblDate
     */
    public javax.swing.JLabel getLblDate() {
        return lblDate;
    }

    /**
     * @param lblDate the lblDate to set
     */
    public void setLblDate(javax.swing.JLabel lblDate) {
        this.lblDate = lblDate;
    }

    /**
     * @return the lblDuration
     */
    public javax.swing.JLabel getLblDuration() {
        return lblDuration;
    }

    /**
     * @param lblDuration the lblDuration to set
     */
    public void setLblDuration(javax.swing.JLabel lblDuration) {
        this.lblDuration = lblDuration;
    }

    /**
     * @return the lblID
     */
    public javax.swing.JLabel getLblID() {
        return lblID;
    }

    /**
     * @param lblID the lblID to set
     */
    public void setLblID(javax.swing.JLabel lblID) {
        this.lblID = lblID;
    }

    /**
     * @return the lblName
     */
    

    /**
     * @return the lblNote
     */
    public javax.swing.JLabel getLblNote() {
        return lblNote;
    }

    /**
     * @param lblNote the lblNote to set
     */
    public void setLblNote(javax.swing.JLabel lblNote) {
        this.lblNote = lblNote;
    }

    /**
     * @return the lblPatient
     */
    public javax.swing.JLabel getLblPatient() {
        return lblPatient;
    }

    /**
     * @param lblPatient the lblPatient to set
     */
    public void setLblPatient(javax.swing.JLabel lblPatient) {
        this.lblPatient = lblPatient;
    }

    /**
     * @return the lblPrice
     */
    public javax.swing.JLabel getLblPrice() {
        return lblPrice;
    }

    /**
     * @param lblPrice the lblPrice to set
     */
    public void setLblPrice(javax.swing.JLabel lblPrice) {
        this.lblPrice = lblPrice;
    }

    /**
     * @return the lblService
     */
    public javax.swing.JLabel getLblService() {
        return lblService;
    }

    /**
     * @param lblService the lblService to set
     */
    public void setLblService(javax.swing.JLabel lblService) {
        this.lblService = lblService;
    }

    /**
     * @return the lblStart
     */
    public javax.swing.JLabel getLblStart() {
        return lblStart;
    }

    /**
     * @param lblStart the lblStart to set
     */
    public void setLblStart(javax.swing.JLabel lblStart) {
        this.lblStart = lblStart;
    }

    /**
     * @return the lblTermin
     */
    public javax.swing.JLabel getLblTermin() {
        return lblTermin;
    }

    /**
     * @param lblTermin the lblTermin to set
     */
    public void setLblTermin(javax.swing.JLabel lblTermin) {
        this.lblTermin = lblTermin;
    }

    /**
     * @return the lblTheEnd
     */
    public javax.swing.JLabel getLblTheEnd() {
        return lblTheEnd;
    }

    /**
     * @param lblTheEnd the lblTheEnd to set
     */
    public void setLblTheEnd(javax.swing.JLabel lblTheEnd) {
        this.lblTheEnd = lblTheEnd;
    }

    /**
     * @return the lblTotalDuration
     */
    public javax.swing.JLabel getLblTotalDuration() {
        return lblTotalDuration;
    }

    /**
     * @param lblTotalDuration the lblTotalDuration to set
     */
    public void setLblTotalDuration(javax.swing.JLabel lblTotalDuration) {
        this.lblTotalDuration = lblTotalDuration;
    }

    /**
     * @return the lblTotalPrice
     */
    public javax.swing.JLabel getLblTotalPrice() {
        return lblTotalPrice;
    }

    /**
     * @param lblTotalPrice the lblTotalPrice to set
     */
    public void setLblTotalPrice(javax.swing.JLabel lblTotalPrice) {
        this.lblTotalPrice = lblTotalPrice;
    }

    /**
     * @return the pn1
     */
    public javax.swing.JPanel getPn1() {
        return pn1;
    }

    /**
     * @param pn1 the pn1 to set
     */
    public void setPn1(javax.swing.JPanel pn1) {
        this.pn1 = pn1;
    }

    /**
     * @return the pnAddExamination
     */
    public javax.swing.JPanel getPnAddExamination() {
        return pnAddExamination;
    }

    /**
     * @param pnAddExamination the pnAddExamination to set
     */
    public void setPnAddExamination(javax.swing.JPanel pnAddExamination) {
        this.pnAddExamination = pnAddExamination;
    }

    /**
     * @return the pnTermin
     */
    public javax.swing.JPanel getPnTermin() {
        return pnTermin;
    }

    /**
     * @param pnTermin the pnTermin to set
     */
    public void setPnTermin(javax.swing.JPanel pnTermin) {
        this.pnTermin = pnTermin;
    }

    /**
     * @return the tblItems
     */
    public javax.swing.JTable getTblItems() {
        return tblItems;
    }

    /**
     * @param tblItems the tblItems to set
     */
    public void setTblItems(javax.swing.JTable tblItems) {
        this.tblItems = tblItems;
    }

    /**
     * @return the txtCurrentDoctor
     */
    public javax.swing.JTextField getTxtCurrentDoctor() {
        return txtCurrentDoctor;
    }

    /**
     * @param txtCurrentDoctor the txtCurrentDoctor to set
     */
    public void setTxtCurrentDoctor(javax.swing.JTextField txtCurrentDoctor) {
        this.txtCurrentDoctor = txtCurrentDoctor;
    }

    /**
     * @return the txtDuration
     */
    public javax.swing.JTextField getTxtDuration() {
        return txtDuration;
    }

    /**
     * @param txtDuration the txtDuration to set
     */
    public void setTxtDuration(javax.swing.JTextField txtDuration) {
        this.txtDuration = txtDuration;
    }

    /**
     * @return the txtID
     */
    public javax.swing.JTextField getTxtID() {
        return txtID;
    }

    /**
     * @param txtID the txtID to set
     */
    public void setTxtID(javax.swing.JTextField txtID) {
        this.txtID = txtID;
    }

    

    /**
     * @return the txtNote
     */
    public javax.swing.JTextArea getTxtNote() {
        return txtNote;
    }

    /**
     * @param txtNote the txtNote to set
     */
    public void setTxtNote(javax.swing.JTextArea txtNote) {
        this.txtNote = txtNote;
    }

    /**
     * @return the txtPrice
     */
    public javax.swing.JTextField getTxtPrice() {
        return txtPrice;
    }

    /**
     * @param txtPrice the txtPrice to set
     */
    public void setTxtPrice(javax.swing.JTextField txtPrice) {
        this.txtPrice = txtPrice;
    }

    /**
     * @return the txtStartHours
     */
    public javax.swing.JTextField getTxtStartHours() {
        return txtStartHours;
    }

    /**
     * @param txtStartHours the txtStartHours to set
     */
    public void setTxtStartHours(javax.swing.JTextField txtStartHours) {
        this.txtStartHours = txtStartHours;
    }

    /**
     * @return the txtStartMinutes
     */
    public javax.swing.JTextField getTxtStartMinutes() {
        return txtStartMinutes;
    }

    /**
     * @param txtStartMinutes the txtStartMinutes to set
     */
    public void setTxtStartMinutes(javax.swing.JTextField txtStartMinutes) {
        this.txtStartMinutes = txtStartMinutes;
    }

    /**
     * @return the txtTheEndHours
     */
    public javax.swing.JTextField getTxtTheEndHours() {
        return txtTheEndHours;
    }

    /**
     * @param txtTheEndHours the txtTheEndHours to set
     */
    public void setTxtTheEndHours(javax.swing.JTextField txtTheEndHours) {
        this.txtTheEndHours = txtTheEndHours;
    }

    /**
     * @return the txtTheEndMinutes
     */
    public javax.swing.JTextField getTxtTheEndMinutes() {
        return txtTheEndMinutes;
    }

    /**
     * @param txtTheEndMinutes the txtTheEndMinutes to set
     */
    public void setTxtTheEndMinutes(javax.swing.JTextField txtTheEndMinutes) {
        this.txtTheEndMinutes = txtTheEndMinutes;
    }

    /**
     * @return the txtTotalDuration
     */
    public javax.swing.JTextField getTxtTotalDuration() {
        return txtTotalDuration;
    }

    /**
     * @param txtTotalDuration the txtTotalDuration to set
     */
    public void setTxtTotalDuration(javax.swing.JTextField txtTotalDuration) {
        this.txtTotalDuration = txtTotalDuration;
    }

    /**
     * @return the txtTotalPrice
     */
    public javax.swing.JTextField getTxtTotalPrice() {
        return txtTotalPrice;
    }

    /**
     * @param txtTotalPrice the txtTotalPrice to set
     */
    public void setTxtTotalPrice(javax.swing.JTextField txtTotalPrice) {
        this.txtTotalPrice = txtTotalPrice;
    }

    public JButton getBtnChoosePatient() {
        return btnChoosePatient;
    }

    public JTextField getTxtPatient() {
        return txtPatient;
    }

    public void setBtnChoosePatient(JButton btnChoosePatient) {
        this.btnChoosePatient = btnChoosePatient;
    }

    public void setTxtPatient(JTextField txtPatient) {
        this.txtPatient = txtPatient;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancelAll;
    private javax.swing.JButton btnChoosePatient;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnableChanges;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JButton btnScheduledTermins;
    private javax.swing.JComboBox<Object> cbPatient;
    private javax.swing.JComboBox<Object> cbService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurrentDuration;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTermin;
    private javax.swing.JLabel lblTheEnd;
    private javax.swing.JLabel lblTotalDuration;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pnAddExamination;
    private javax.swing.JPanel pnTermin;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtCurrentDoctor;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtPatient;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStartHours;
    private javax.swing.JTextField txtStartMinutes;
    private javax.swing.JTextField txtTheEndHours;
    private javax.swing.JTextField txtTheEndMinutes;
    private javax.swing.JTextField txtTotalDuration;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    public void btnAddItemAddActionListener(ActionListener actionListener) {
        btnAddItem.addActionListener(actionListener);
    }

    public void btnDeleteItemAddActionListener(ActionListener actionListener) {
        btnDeleteItem.addActionListener(actionListener);
    }

    public void btnCancelAllAddActionListener(ActionListener actionListener) {
        btnCancelAll.addActionListener(actionListener);
    }

    public void btnSaveAllAddActionListener(ActionListener actionListener) {
        btnSaveAll.addActionListener(actionListener);
    }

    public void btnEnableChangesAddActionListener(ActionListener actionListener) {
        btnEnableChanges.addActionListener(actionListener);
    }

    public void btnEditAddActionListener(ActionListener actionListener) {
        btnEdit.addActionListener(actionListener);
    }

    public void btnDeleteAddActionListener(ActionListener actionListener) {
        btnDelete.addActionListener(actionListener);
    }
    
    public void btnScheduledTerminsAddActionListener(ActionListener actionListener) {
        btnScheduledTermins.addActionListener(actionListener);
    }
    
    public void cbServiceAddActionListener(ActionListener actionListener){
        cbService.addActionListener(actionListener);
    }
    
    public void btnChoosePatientAddActionListener(ActionListener actionListener){
        btnChoosePatient.addActionListener(actionListener);
    }
}
