/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Zbook G3
 */
public class FrmScheduledTermins extends javax.swing.JDialog {

    /**
     * Creates new form FrmScheduledTermins
     */
    public FrmScheduledTermins(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnScheduledTermins = new javax.swing.JPanel();
        lblSearchValue = new javax.swing.JLabel();
        txtSearchValue = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSheduledTermins = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSearchValue.setText("Please, enter the value by which you search the termin:");

        btnCancel.setText("Cancel");

        tblSheduledTermins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSheduledTermins);

        jLabel1.setText("Your scheduled termins:");

        javax.swing.GroupLayout pnScheduledTerminsLayout = new javax.swing.GroupLayout(pnScheduledTermins);
        pnScheduledTermins.setLayout(pnScheduledTerminsLayout);
        pnScheduledTerminsLayout.setHorizontalGroup(
            pnScheduledTerminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnScheduledTerminsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnScheduledTerminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnScheduledTerminsLayout.createSequentialGroup()
                        .addGroup(pnScheduledTerminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearchValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearchValue, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnScheduledTerminsLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnScheduledTerminsLayout.setVerticalGroup(
            pnScheduledTerminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnScheduledTerminsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnScheduledTerminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSearchValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnScheduledTermins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnScheduledTermins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    /**
     * @return the btnCancel
     */
    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * @param btnCancel the btnCancel to set
     */
    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the lblSearchValue
     */
    public javax.swing.JLabel getLblSearchValue() {
        return lblSearchValue;
    }

    /**
     * @param lblSearchValue the lblSearchValue to set
     */
    public void setLblSearchValue(javax.swing.JLabel lblSearchValue) {
        this.lblSearchValue = lblSearchValue;
    }

    /**
     * @return the pnScheduledTermins
     */
    public javax.swing.JPanel getPnScheduledTermins() {
        return pnScheduledTermins;
    }

    /**
     * @param pnScheduledTermins the pnScheduledTermins to set
     */
    public void setPnScheduledTermins(javax.swing.JPanel pnScheduledTermins) {
        this.pnScheduledTermins = pnScheduledTermins;
    }

    /**
     * @return the tblSheduledTermins
     */
    public javax.swing.JTable getTblSheduledTermins() {
        return tblSheduledTermins;
    }

    /**
     * @param tblSheduledTermins the tblSheduledTermins to set
     */
    public void setTblSheduledTermins(javax.swing.JTable tblSheduledTermins) {
        this.tblSheduledTermins = tblSheduledTermins;
    }

    /**
     * @return the txtSearchValue
     */
    public javax.swing.JTextField getTxtSearchValue() {
        return txtSearchValue;
    }

    /**
     * @param txtSearchValue the txtSearchValue to set
     */
    public void setTxtSearchValue(javax.swing.JTextField txtSearchValue) {
        this.txtSearchValue = txtSearchValue;
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchValue;
    private javax.swing.JPanel pnScheduledTermins;
    private javax.swing.JTable tblSheduledTermins;
    private javax.swing.JTextField txtSearchValue;
    // End of variables declaration//GEN-END:variables

    
    public void btnCancelAddActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

}
