/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Zbook G3
 */
public class FrmViewAllExaminations extends javax.swing.JDialog {

    /**
     * Creates new form FrmViewAllExaminations
     */
    public FrmViewAllExaminations(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnViewAllExaminations = new javax.swing.JPanel();
        lblSearchValue = new javax.swing.JLabel();
        txtSearchValue = new javax.swing.JTextField();
        btnDetails = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExaminations = new javax.swing.JTable();
        txtEmptyValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSearchValue.setText("Please, enter the value by which you search the examination:");

        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        tblExaminations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblExaminations);

        javax.swing.GroupLayout pnViewAllExaminationsLayout = new javax.swing.GroupLayout(pnViewAllExaminations);
        pnViewAllExaminations.setLayout(pnViewAllExaminationsLayout);
        pnViewAllExaminationsLayout.setHorizontalGroup(
            pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViewAllExaminationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnViewAllExaminationsLayout.createSequentialGroup()
                        .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearchValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchValue))
                        .addGap(73, 73, 73)
                        .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(pnViewAllExaminationsLayout.createSequentialGroup()
                        .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmptyValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnViewAllExaminationsLayout.setVerticalGroup(
            pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViewAllExaminationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchValue, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnViewAllExaminationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmptyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnViewAllExaminations, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnViewAllExaminations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    

     /**
     * @return the btnCancel
     */
    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * @param btnCancel the btnCancel to set
     */
    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    /**
     * @return the btnDetails
     */
    public javax.swing.JButton getBtnDetails() {
        return btnDetails;
    }

    /**
     * @param btnDetails the btnDetails to set
     */
    public void setBtnDetails(javax.swing.JButton btnDetails) {
        this.btnDetails = btnDetails;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the lblSearchValue
     */
    public javax.swing.JLabel getLblSearchValue() {
        return lblSearchValue;
    }

    /**
     * @param lblSearchValue the lblSearchValue to set
     */
    public void setLblSearchValue(javax.swing.JLabel lblSearchValue) {
        this.lblSearchValue = lblSearchValue;
    }

    /**
     * @return the pnViewAllExaminations
     */
    public javax.swing.JPanel getPnViewAllExaminations() {
        return pnViewAllExaminations;
    }

    /**
     * @param pnViewAllExaminations the pnViewAllExaminations to set
     */
    public void setPnViewAllExaminations(javax.swing.JPanel pnViewAllExaminations) {
        this.pnViewAllExaminations = pnViewAllExaminations;
    }

    /**
     * @return the tblExaminations
     */
    public javax.swing.JTable getTblExaminations() {
        return tblExaminations;
    }

    /**
     * @param tblExaminations the tblExaminations to set
     */
    public void setTblExaminations(javax.swing.JTable tblExaminations) {
        this.tblExaminations = tblExaminations;
    }

    /**
     * @return the txtEmptyTable
     */
    public javax.swing.JTextField getTxtEmptyValue() {
        return txtEmptyValue;
    }

    /**
     * @param txtEmptyTable the txtEmptyTable to set
     */
    public void setTxtEmptyValue(javax.swing.JTextField txtEmptyTable) {
        this.txtEmptyValue = txtEmptyTable;
    }

    /**
     * @return the txtSearchValue
     */
    public javax.swing.JTextField getTxtSearchValue() {
        return txtSearchValue;
    }

    /**
     * @param txtSearchValue the txtSearchValue to set
     */
    public void setTxtSearchValue(javax.swing.JTextField txtSearchValue) {
        this.txtSearchValue = txtSearchValue;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchValue;
    private javax.swing.JPanel pnViewAllExaminations;
    private javax.swing.JTable tblExaminations;
    private javax.swing.JTextField txtEmptyValue;
    private javax.swing.JTextField txtSearchValue;
    // End of variables declaration//GEN-END:variables

   
    public void btnDetailsAddAcionListener(ActionListener actionListener) {
        btnDetails.addActionListener(actionListener);
    }
    
    public void btnCancelAddAcionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }
    
}
